// Code generated by mockery v2.9.4. DO NOT EDIT.

package services

import (
	entities "github.com/mannyOaks/academy-go-q32021/entities"
	mock "github.com/stretchr/testify/mock"
)

// mockMovieRepository is an autogenerated mock type for the movieRepository type
type mockMovieRepository struct {
	mock.Mock
}

// GetMovie provides a mock function with given fields: id
func (_m *mockMovieRepository) GetMovie(id string) (entities.Movie, error) {
	ret := _m.Called(id)

	var r0 entities.Movie
	if rf, ok := ret.Get(0).(func(string) entities.Movie); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Get(0).(entities.Movie)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
