// Code generated by mockery v2.9.4. DO NOT EDIT.

package services

import (
	common "mrobles_app/common"

	mock "github.com/stretchr/testify/mock"
)

// mockRepository is an autogenerated mock type for the repository type
type mockRepository struct {
	mock.Mock
}

// GetMovie provides a mock function with given fields: id
func (_m *mockRepository) GetMovie(id string) (common.Movie, error) {
	ret := _m.Called(id)

	var r0 common.Movie
	if rf, ok := ret.Get(0).(func(string) common.Movie); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Get(0).(common.Movie)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
