// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	entities "github.com/mannyOaks/academy-go-q32021/entities"
	mock "github.com/stretchr/testify/mock"
)

// WorkerPool is an autogenerated mock type for the WorkerPool type
type WorkerPool struct {
	mock.Mock
}

// GetMovies provides a mock function with given fields: _a0, _a1, _a2, _a3
func (_m *WorkerPool) GetMovies(_a0 string, _a1 int, _a2 int, _a3 int) ([]entities.Movie, error) {
	ret := _m.Called(_a0, _a1, _a2, _a3)

	var r0 []entities.Movie
	if rf, ok := ret.Get(0).(func(string, int, int, int) []entities.Movie); ok {
		r0 = rf(_a0, _a1, _a2, _a3)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entities.Movie)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, int, int, int) error); ok {
		r1 = rf(_a0, _a1, _a2, _a3)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
